schema: schema.graphql
extensions:
  endpoints:
    Default GraphQL Endpoint:
      url: https://inventai-6798a275a85f.herokuapp.com/api/v1/open/graphql/
      headers:
        user-agent: JS GraphQL
      introspect: false
